name: xzn
description: A new Flutter application serving monkeys

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  http: ^0.12.0
  dio: ^3.0.9
  shared_preferences: ^0.5.1+1
  cached_network_image: ^2.0.0
  flutter_webview_plugin: ^0.3.11
  flutter_swiper: ^1.1.5
  share: 0.6.2
  path_provider: ^1.6.9
  intl: ^0.16.0
  image_picker: ^0.6.7+1
  image_crop: ^0.3.2
  permission_handler: ^5.0.1
#  flutter_amap: ^0.0.1
  amap_map_fluttify: ^0.23.2
#  flutter_alipay: ^0.1.0
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model: ^0.0.2
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  intl_translation: ^0.17.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/swiper/1.webp
    - assets/image/swiper/2.webp
    - assets/image/swiper/3.webp
    - assets/image/swiper/4.webp
    - assets/image/swiper/5.webp

    - assets/image/load/1.webp
    - assets/image/load/2.webp
    - assets/image/load/3.webp
    - assets/image/load/4.webp
    - assets/image/load/5.webp

    - assets/image/class/1.png
    - assets/image/class/2.png
    - assets/image/class/3.png
    - assets/image/class/4.png
    - assets/image/class/5.png

    - assets/image/login_logo.webp
    - assets/image/qrcode.webp
    - assets/image/no_login.webp

    - assets/image/ads/1.webp
    - assets/image/ads/2.webp
    - assets/image/ads/3.webp
    - assets/image/ads/4.webp
    - assets/image/ads/5.webp

    - assets/image/avatar_default_1.webp
    - assets/image/avatar_default_2.webp
    - assets/image/avatar_default_3.webp
    - assets/image/avatar_default_4.webp
    - assets/image/avatar_default_5.webp
    - assets/image/avatar_default_6.webp
    - assets/image/avatar_default_7.webp
    - assets/image/avatar_default_8.webp
    - assets/image/default_picture.webp

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
